// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLCdGRq5gwwYw6PFBqN89zCAMYAppzoTM',
    appId: '1:954058262748:web:cf1bec8bce0b5a48ef0c19',
    messagingSenderId: '954058262748',
    projectId: 'fir-23-7c27c',
    authDomain: 'fir-23-7c27c.firebaseapp.com',
    storageBucket: 'fir-23-7c27c.appspot.com',
    measurementId: 'G-JPLVPYKN0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiYDwG7rBHjZ5TX-n6wFrvonIKEVr8gi0',
    appId: '1:954058262748:android:a74db7ff7d8056cdef0c19',
    messagingSenderId: '954058262748',
    projectId: 'fir-23-7c27c',
    storageBucket: 'fir-23-7c27c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4VZmsQQFDkjBLi8e9rFPfQOn09uU5880',
    appId: '1:954058262748:ios:1949b1ebe11ae7c6ef0c19',
    messagingSenderId: '954058262748',
    projectId: 'fir-23-7c27c',
    storageBucket: 'fir-23-7c27c.appspot.com',
    iosClientId: '954058262748-n1ldln76df98scmavagv9bgiktos4cki.apps.googleusercontent.com',
    iosBundleId: 'com.example.h1zen',
  );
}
